/*
 - Copyright 1999-2016 Shanghai XiangTu Network Technology Co. Limit
*/
package com.cys.user.dao;

import com.cys.user.model.OauthUserExample;
import java.util.List;

import com.cys.user.pojo.OauthUser;
import org.apache.ibatis.annotations.Param;

public interface OauthUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cys_oauth_user
     *
     * @mbggenerated
     */
    int countByExample(OauthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cys_oauth_user
     *
     * @mbggenerated
     */
    int deleteByExample(OauthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cys_oauth_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cys_oauth_user
     *
     * @mbggenerated
     */
    int insert(OauthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cys_oauth_user
     *
     * @mbggenerated
     */
    int insertSelective(OauthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cys_oauth_user
     *
     * @mbggenerated
     */
    List<OauthUser> selectByExample(OauthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cys_oauth_user
     *
     * @mbggenerated
     */
    OauthUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cys_oauth_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OauthUser record, @Param("example") OauthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cys_oauth_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OauthUser record, @Param("example") OauthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cys_oauth_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OauthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cys_oauth_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OauthUser record);
}