/*
 - Copyright 1999-2016 Shanghai XiangTu Network Technology Co. Limit
*/
/*
 - Copyright 1999-2016 Shanghai XiangTu Network Technology Co. Limit
*/
package com.cys.user.pojo;

import com.esotericsoftware.kryo.DefaultSerializer;
import com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer;
import java.io.Serializable;

/**
* OauthUser设置Kryo的CompatibleFieldSerializer
* Auto generated by Stanley Li
*/
@DefaultSerializer(CompatibleFieldSerializer.class)
public class OauthUser implements Serializable {
    /**
     * cys_oauth_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * 用户ID
     * cys_oauth_user.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * 第三方用户昵称
     * cys_oauth_user.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * 第三方用户关联OpenID,针对微信为union_id
     * cys_oauth_user.openid
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * 扩展的openid
     * cys_oauth_user.ext_openid
     *
     * @mbggenerated
     */
    private String extOpenid;

    /**
     * oauth提供方
     * cys_oauth_user.provider
     *
     * @mbggenerated
     */
    private String provider;

    /**
     * oauth提供方的app_id
     * cys_oauth_user.provider_id
     *
     * @mbggenerated
     */
    private String providerId;

    /**
     * 是否关注 0关注 1关注
     * cys_oauth_user.is_subscribe
     *
     * @mbggenerated
     */
    private Byte isSubscribe;

    /**
     * 性别 1男 2女
     * cys_oauth_user.gender
     *
     * @mbggenerated
     */
    private Byte gender;

    /**
     * 头像URL
     * cys_oauth_user.face_img
     *
     * @mbggenerated
     */
    private String faceImg;

    /**
     * 从OAuth提供方获取的用户信息
     * cys_oauth_user.user_info
     *
     * @mbggenerated
     */
    private String userInfo;

    /**
     * cys_oauth_user.created_time
     *
     * @mbggenerated
     */
    private Long createdTime;

    /**
     * cys_oauth_user.updated_time
     *
     * @mbggenerated
     */
    private Long updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cys_oauth_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method returns the value of the database column cys_oauth_user.id
     *
     * @return the value of cys_oauth_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method sets the value of the database column cys_oauth_user.id
     *
     * @param id the value for cys_oauth_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 用户ID
     * This method returns the value of the database column cys_oauth_user.user_id
     *
     * @return the value of cys_oauth_user.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * 用户ID
     * This method sets the value of the database column cys_oauth_user.user_id
     *
     * @param userId the value for cys_oauth_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * 第三方用户昵称
     * This method returns the value of the database column cys_oauth_user.nickname
     *
     * @return the value of cys_oauth_user.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * 第三方用户昵称
     * This method sets the value of the database column cys_oauth_user.nickname
     *
     * @param nickname the value for cys_oauth_user.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * 第三方用户关联OpenID,针对微信为union_id
     * This method returns the value of the database column cys_oauth_user.openid
     *
     * @return the value of cys_oauth_user.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * 第三方用户关联OpenID,针对微信为union_id
     * This method sets the value of the database column cys_oauth_user.openid
     *
     * @param openid the value for cys_oauth_user.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * 扩展的openid
     * This method returns the value of the database column cys_oauth_user.ext_openid
     *
     * @return the value of cys_oauth_user.ext_openid
     *
     * @mbggenerated
     */
    public String getExtOpenid() {
        return extOpenid;
    }

    /**
     * 扩展的openid
     * This method sets the value of the database column cys_oauth_user.ext_openid
     *
     * @param extOpenid the value for cys_oauth_user.ext_openid
     *
     * @mbggenerated
     */
    public void setExtOpenid(String extOpenid) {
        this.extOpenid = extOpenid;
    }

    /**
     * oauth提供方
     * This method returns the value of the database column cys_oauth_user.provider
     *
     * @return the value of cys_oauth_user.provider
     *
     * @mbggenerated
     */
    public String getProvider() {
        return provider;
    }

    /**
     * oauth提供方
     * This method sets the value of the database column cys_oauth_user.provider
     *
     * @param provider the value for cys_oauth_user.provider
     *
     * @mbggenerated
     */
    public void setProvider(String provider) {
        this.provider = provider;
    }

    /**
     * oauth提供方的app_id
     * This method returns the value of the database column cys_oauth_user.provider_id
     *
     * @return the value of cys_oauth_user.provider_id
     *
     * @mbggenerated
     */
    public String getProviderId() {
        return providerId;
    }

    /**
     * oauth提供方的app_id
     * This method sets the value of the database column cys_oauth_user.provider_id
     *
     * @param providerId the value for cys_oauth_user.provider_id
     *
     * @mbggenerated
     */
    public void setProviderId(String providerId) {
        this.providerId = providerId;
    }

    /**
     * 是否关注 0关注 1关注
     * This method returns the value of the database column cys_oauth_user.is_subscribe
     *
     * @return the value of cys_oauth_user.is_subscribe
     *
     * @mbggenerated
     */
    public Byte getIsSubscribe() {
        return isSubscribe;
    }

    /**
     * 是否关注 0关注 1关注
     * This method sets the value of the database column cys_oauth_user.is_subscribe
     *
     * @param isSubscribe the value for cys_oauth_user.is_subscribe
     *
     * @mbggenerated
     */
    public void setIsSubscribe(Byte isSubscribe) {
        this.isSubscribe = isSubscribe;
    }

    /**
     * 性别 1男 2女
     * This method returns the value of the database column cys_oauth_user.gender
     *
     * @return the value of cys_oauth_user.gender
     *
     * @mbggenerated
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * 性别 1男 2女
     * This method sets the value of the database column cys_oauth_user.gender
     *
     * @param gender the value for cys_oauth_user.gender
     *
     * @mbggenerated
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * 头像URL
     * This method returns the value of the database column cys_oauth_user.face_img
     *
     * @return the value of cys_oauth_user.face_img
     *
     * @mbggenerated
     */
    public String getFaceImg() {
        return faceImg;
    }

    /**
     * 头像URL
     * This method sets the value of the database column cys_oauth_user.face_img
     *
     * @param faceImg the value for cys_oauth_user.face_img
     *
     * @mbggenerated
     */
    public void setFaceImg(String faceImg) {
        this.faceImg = faceImg;
    }

    /**
     * 从OAuth提供方获取的用户信息
     * This method returns the value of the database column cys_oauth_user.user_info
     *
     * @return the value of cys_oauth_user.user_info
     *
     * @mbggenerated
     */
    public String getUserInfo() {
        return userInfo;
    }

    /**
     * 从OAuth提供方获取的用户信息
     * This method sets the value of the database column cys_oauth_user.user_info
     *
     * @param userInfo the value for cys_oauth_user.user_info
     *
     * @mbggenerated
     */
    public void setUserInfo(String userInfo) {
        this.userInfo = userInfo;
    }

    /**
     * This method returns the value of the database column cys_oauth_user.created_time
     *
     * @return the value of cys_oauth_user.created_time
     *
     * @mbggenerated
     */
    public Long getCreatedTime() {
        return createdTime;
    }

    /**
     * This method sets the value of the database column cys_oauth_user.created_time
     *
     * @param createdTime the value for cys_oauth_user.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Long createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method returns the value of the database column cys_oauth_user.updated_time
     *
     * @return the value of cys_oauth_user.updated_time
     *
     * @mbggenerated
     */
    public Long getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method sets the value of the database column cys_oauth_user.updated_time
     *
     * @param updatedTime the value for cys_oauth_user.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Long updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cys_oauth_user
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OauthUser other = (OauthUser) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getNickname() == null ? other.getNickname() == null : this.getNickname().equals(other.getNickname()))
            && (this.getOpenid() == null ? other.getOpenid() == null : this.getOpenid().equals(other.getOpenid()))
            && (this.getExtOpenid() == null ? other.getExtOpenid() == null : this.getExtOpenid().equals(other.getExtOpenid()))
            && (this.getProvider() == null ? other.getProvider() == null : this.getProvider().equals(other.getProvider()))
            && (this.getProviderId() == null ? other.getProviderId() == null : this.getProviderId().equals(other.getProviderId()))
            && (this.getIsSubscribe() == null ? other.getIsSubscribe() == null : this.getIsSubscribe().equals(other.getIsSubscribe()))
            && (this.getGender() == null ? other.getGender() == null : this.getGender().equals(other.getGender()))
            && (this.getFaceImg() == null ? other.getFaceImg() == null : this.getFaceImg().equals(other.getFaceImg()))
            && (this.getUserInfo() == null ? other.getUserInfo() == null : this.getUserInfo().equals(other.getUserInfo()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getUpdatedTime() == null ? other.getUpdatedTime() == null : this.getUpdatedTime().equals(other.getUpdatedTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cys_oauth_user
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getNickname() == null) ? 0 : getNickname().hashCode());
        result = prime * result + ((getOpenid() == null) ? 0 : getOpenid().hashCode());
        result = prime * result + ((getExtOpenid() == null) ? 0 : getExtOpenid().hashCode());
        result = prime * result + ((getProvider() == null) ? 0 : getProvider().hashCode());
        result = prime * result + ((getProviderId() == null) ? 0 : getProviderId().hashCode());
        result = prime * result + ((getIsSubscribe() == null) ? 0 : getIsSubscribe().hashCode());
        result = prime * result + ((getGender() == null) ? 0 : getGender().hashCode());
        result = prime * result + ((getFaceImg() == null) ? 0 : getFaceImg().hashCode());
        result = prime * result + ((getUserInfo() == null) ? 0 : getUserInfo().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cys_oauth_user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", nickname=").append(nickname);
        sb.append(", openid=").append(openid);
        sb.append(", extOpenid=").append(extOpenid);
        sb.append(", provider=").append(provider);
        sb.append(", providerId=").append(providerId);
        sb.append(", isSubscribe=").append(isSubscribe);
        sb.append(", gender=").append(gender);
        sb.append(", faceImg=").append(faceImg);
        sb.append(", userInfo=").append(userInfo);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}