/*
 - Copyright 1999-2016 Shanghai XiangTu Network Technology Co. Limit
*/
/*
 - Copyright 1999-2016 Shanghai XiangTu Network Technology Co. Limit
*/
package com.cys.user.pojo;

import com.esotericsoftware.kryo.DefaultSerializer;
import com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer;
import java.io.Serializable;
import java.util.Date;

/**
* UserInfo设置Kryo的CompatibleFieldSerializer
* Auto generated by Stanley Li
*/
@DefaultSerializer(CompatibleFieldSerializer.class)
public class UserInfo implements Serializable {
    /**
     * cys_user_info.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * UC中心用户ID
     * cys_user_info.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * 真实姓名
     * cys_user_info.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * 昵称
     * cys_user_info.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * 性别 1男 2女
     * cys_user_info.gender
     *
     * @mbggenerated
     */
    private Byte gender;

    /**
     * 生日
     * cys_user_info.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * 居住地id
     * cys_user_info.place_id
     *
     * @mbggenerated
     */
    private Integer placeId;

    /**
     * 家乡ID
     * cys_user_info.hometown
     *
     * @mbggenerated
     */
    private Integer hometown;

    /**
     * 详细地址(精确到路、街道、门牌号)
     * cys_user_info.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * 头像图片在图片服务器存储相对URL
     * cys_user_info.face_image_url
     *
     * @mbggenerated
     */
    private String faceImageUrl;

    /**
     * 简介
     * cys_user_info.intro
     *
     * @mbggenerated
     */
    private String intro;

    /**
     * 创建时间
     * cys_user_info.created_time
     *
     * @mbggenerated
     */
    private Long createdTime;

    /**
     * 更新时间
     * cys_user_info.updated_time
     *
     * @mbggenerated
     */
    private Long updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cys_user_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method returns the value of the database column cys_user_info.id
     *
     * @return the value of cys_user_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method sets the value of the database column cys_user_info.id
     *
     * @param id the value for cys_user_info.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * UC中心用户ID
     * This method returns the value of the database column cys_user_info.user_id
     *
     * @return the value of cys_user_info.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * UC中心用户ID
     * This method sets the value of the database column cys_user_info.user_id
     *
     * @param userId the value for cys_user_info.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * 真实姓名
     * This method returns the value of the database column cys_user_info.real_name
     *
     * @return the value of cys_user_info.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * 真实姓名
     * This method sets the value of the database column cys_user_info.real_name
     *
     * @param realName the value for cys_user_info.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * 昵称
     * This method returns the value of the database column cys_user_info.nick_name
     *
     * @return the value of cys_user_info.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * 昵称
     * This method sets the value of the database column cys_user_info.nick_name
     *
     * @param nickName the value for cys_user_info.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * 性别 1男 2女
     * This method returns the value of the database column cys_user_info.gender
     *
     * @return the value of cys_user_info.gender
     *
     * @mbggenerated
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * 性别 1男 2女
     * This method sets the value of the database column cys_user_info.gender
     *
     * @param gender the value for cys_user_info.gender
     *
     * @mbggenerated
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * 生日
     * This method returns the value of the database column cys_user_info.birthday
     *
     * @return the value of cys_user_info.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * 生日
     * This method sets the value of the database column cys_user_info.birthday
     *
     * @param birthday the value for cys_user_info.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * 居住地id
     * This method returns the value of the database column cys_user_info.place_id
     *
     * @return the value of cys_user_info.place_id
     *
     * @mbggenerated
     */
    public Integer getPlaceId() {
        return placeId;
    }

    /**
     * 居住地id
     * This method sets the value of the database column cys_user_info.place_id
     *
     * @param placeId the value for cys_user_info.place_id
     *
     * @mbggenerated
     */
    public void setPlaceId(Integer placeId) {
        this.placeId = placeId;
    }

    /**
     * 家乡ID
     * This method returns the value of the database column cys_user_info.hometown
     *
     * @return the value of cys_user_info.hometown
     *
     * @mbggenerated
     */
    public Integer getHometown() {
        return hometown;
    }

    /**
     * 家乡ID
     * This method sets the value of the database column cys_user_info.hometown
     *
     * @param hometown the value for cys_user_info.hometown
     *
     * @mbggenerated
     */
    public void setHometown(Integer hometown) {
        this.hometown = hometown;
    }

    /**
     * 详细地址(精确到路、街道、门牌号)
     * This method returns the value of the database column cys_user_info.address
     *
     * @return the value of cys_user_info.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * 详细地址(精确到路、街道、门牌号)
     * This method sets the value of the database column cys_user_info.address
     *
     * @param address the value for cys_user_info.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * 头像图片在图片服务器存储相对URL
     * This method returns the value of the database column cys_user_info.face_image_url
     *
     * @return the value of cys_user_info.face_image_url
     *
     * @mbggenerated
     */
    public String getFaceImageUrl() {
        return faceImageUrl;
    }

    /**
     * 头像图片在图片服务器存储相对URL
     * This method sets the value of the database column cys_user_info.face_image_url
     *
     * @param faceImageUrl the value for cys_user_info.face_image_url
     *
     * @mbggenerated
     */
    public void setFaceImageUrl(String faceImageUrl) {
        this.faceImageUrl = faceImageUrl;
    }

    /**
     * 简介
     * This method returns the value of the database column cys_user_info.intro
     *
     * @return the value of cys_user_info.intro
     *
     * @mbggenerated
     */
    public String getIntro() {
        return intro;
    }

    /**
     * 简介
     * This method sets the value of the database column cys_user_info.intro
     *
     * @param intro the value for cys_user_info.intro
     *
     * @mbggenerated
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }

    /**
     * 创建时间
     * This method returns the value of the database column cys_user_info.created_time
     *
     * @return the value of cys_user_info.created_time
     *
     * @mbggenerated
     */
    public Long getCreatedTime() {
        return createdTime;
    }

    /**
     * 创建时间
     * This method sets the value of the database column cys_user_info.created_time
     *
     * @param createdTime the value for cys_user_info.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Long createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * 更新时间
     * This method returns the value of the database column cys_user_info.updated_time
     *
     * @return the value of cys_user_info.updated_time
     *
     * @mbggenerated
     */
    public Long getUpdatedTime() {
        return updatedTime;
    }

    /**
     * 更新时间
     * This method sets the value of the database column cys_user_info.updated_time
     *
     * @param updatedTime the value for cys_user_info.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Long updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cys_user_info
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserInfo other = (UserInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getRealName() == null ? other.getRealName() == null : this.getRealName().equals(other.getRealName()))
            && (this.getNickName() == null ? other.getNickName() == null : this.getNickName().equals(other.getNickName()))
            && (this.getGender() == null ? other.getGender() == null : this.getGender().equals(other.getGender()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getPlaceId() == null ? other.getPlaceId() == null : this.getPlaceId().equals(other.getPlaceId()))
            && (this.getHometown() == null ? other.getHometown() == null : this.getHometown().equals(other.getHometown()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getFaceImageUrl() == null ? other.getFaceImageUrl() == null : this.getFaceImageUrl().equals(other.getFaceImageUrl()))
            && (this.getIntro() == null ? other.getIntro() == null : this.getIntro().equals(other.getIntro()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getUpdatedTime() == null ? other.getUpdatedTime() == null : this.getUpdatedTime().equals(other.getUpdatedTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cys_user_info
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getRealName() == null) ? 0 : getRealName().hashCode());
        result = prime * result + ((getNickName() == null) ? 0 : getNickName().hashCode());
        result = prime * result + ((getGender() == null) ? 0 : getGender().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getPlaceId() == null) ? 0 : getPlaceId().hashCode());
        result = prime * result + ((getHometown() == null) ? 0 : getHometown().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getFaceImageUrl() == null) ? 0 : getFaceImageUrl().hashCode());
        result = prime * result + ((getIntro() == null) ? 0 : getIntro().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cys_user_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", realName=").append(realName);
        sb.append(", nickName=").append(nickName);
        sb.append(", gender=").append(gender);
        sb.append(", birthday=").append(birthday);
        sb.append(", placeId=").append(placeId);
        sb.append(", hometown=").append(hometown);
        sb.append(", address=").append(address);
        sb.append(", faceImageUrl=").append(faceImageUrl);
        sb.append(", intro=").append(intro);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}