/*
 - Copyright 1999-2016 Shanghai XiangTu Network Technology Co. Limit
*/
/*
 - Copyright 1999-2016 Shanghai XiangTu Network Technology Co. Limit
*/
package com.cys.user.pojo;

import com.esotericsoftware.kryo.DefaultSerializer;
import com.esotericsoftware.kryo.serializers.CompatibleFieldSerializer;
import java.io.Serializable;

/**
* User设置Kryo的CompatibleFieldSerializer
* Auto generated by Stanley Li
*/
@DefaultSerializer(CompatibleFieldSerializer.class)
public class User implements Serializable {
    /**
     * cys_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * 用户名
     * cys_user.login_name
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * 密码
     * cys_user.passwd
     *
     * @mbggenerated
     */
    private String passwd;

    /**
     * 电子邮件
     * cys_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * 手机号码
     * cys_user.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * 邮件绑定状态 0未绑定 1绑定
     * cys_user.email_status
     *
     * @mbggenerated
     */
    private Byte emailStatus;

    /**
     * 手机绑定状态 0未绑定 1绑定
     * cys_user.mobile_status
     *
     * @mbggenerated
     */
    private Byte mobileStatus;

    /**
     * 注册IP地址
     * cys_user.register_ip
     *
     * @mbggenerated
     */
    private String registerIp;

    /**
     * 用户状态 1激活 0未激活
     * cys_user.user_status
     *
     * @mbggenerated
     */
    private Byte userStatus;

    /**
     * 最后更新时间
     * cys_user.updated_time
     *
     * @mbggenerated
     */
    private Long updatedTime;

    /**
     * 注册时间
     * cys_user.created_time
     *
     * @mbggenerated
     */
    private Long createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cys_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method returns the value of the database column cys_user.id
     *
     * @return the value of cys_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method sets the value of the database column cys_user.id
     *
     * @param id the value for cys_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 用户名
     * This method returns the value of the database column cys_user.login_name
     *
     * @return the value of cys_user.login_name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * 用户名
     * This method sets the value of the database column cys_user.login_name
     *
     * @param loginName the value for cys_user.login_name
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * 密码
     * This method returns the value of the database column cys_user.passwd
     *
     * @return the value of cys_user.passwd
     *
     * @mbggenerated
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * 密码
     * This method sets the value of the database column cys_user.passwd
     *
     * @param passwd the value for cys_user.passwd
     *
     * @mbggenerated
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * 电子邮件
     * This method returns the value of the database column cys_user.email
     *
     * @return the value of cys_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * 电子邮件
     * This method sets the value of the database column cys_user.email
     *
     * @param email the value for cys_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * 手机号码
     * This method returns the value of the database column cys_user.mobile
     *
     * @return the value of cys_user.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * 手机号码
     * This method sets the value of the database column cys_user.mobile
     *
     * @param mobile the value for cys_user.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * 邮件绑定状态 0未绑定 1绑定
     * This method returns the value of the database column cys_user.email_status
     *
     * @return the value of cys_user.email_status
     *
     * @mbggenerated
     */
    public Byte getEmailStatus() {
        return emailStatus;
    }

    /**
     * 邮件绑定状态 0未绑定 1绑定
     * This method sets the value of the database column cys_user.email_status
     *
     * @param emailStatus the value for cys_user.email_status
     *
     * @mbggenerated
     */
    public void setEmailStatus(Byte emailStatus) {
        this.emailStatus = emailStatus;
    }

    /**
     * 手机绑定状态 0未绑定 1绑定
     * This method returns the value of the database column cys_user.mobile_status
     *
     * @return the value of cys_user.mobile_status
     *
     * @mbggenerated
     */
    public Byte getMobileStatus() {
        return mobileStatus;
    }

    /**
     * 手机绑定状态 0未绑定 1绑定
     * This method sets the value of the database column cys_user.mobile_status
     *
     * @param mobileStatus the value for cys_user.mobile_status
     *
     * @mbggenerated
     */
    public void setMobileStatus(Byte mobileStatus) {
        this.mobileStatus = mobileStatus;
    }

    /**
     * 注册IP地址
     * This method returns the value of the database column cys_user.register_ip
     *
     * @return the value of cys_user.register_ip
     *
     * @mbggenerated
     */
    public String getRegisterIp() {
        return registerIp;
    }

    /**
     * 注册IP地址
     * This method sets the value of the database column cys_user.register_ip
     *
     * @param registerIp the value for cys_user.register_ip
     *
     * @mbggenerated
     */
    public void setRegisterIp(String registerIp) {
        this.registerIp = registerIp;
    }

    /**
     * 用户状态 1激活 0未激活
     * This method returns the value of the database column cys_user.user_status
     *
     * @return the value of cys_user.user_status
     *
     * @mbggenerated
     */
    public Byte getUserStatus() {
        return userStatus;
    }

    /**
     * 用户状态 1激活 0未激活
     * This method sets the value of the database column cys_user.user_status
     *
     * @param userStatus the value for cys_user.user_status
     *
     * @mbggenerated
     */
    public void setUserStatus(Byte userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * 最后更新时间
     * This method returns the value of the database column cys_user.updated_time
     *
     * @return the value of cys_user.updated_time
     *
     * @mbggenerated
     */
    public Long getUpdatedTime() {
        return updatedTime;
    }

    /**
     * 最后更新时间
     * This method sets the value of the database column cys_user.updated_time
     *
     * @param updatedTime the value for cys_user.updated_time
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Long updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * 注册时间
     * This method returns the value of the database column cys_user.created_time
     *
     * @return the value of cys_user.created_time
     *
     * @mbggenerated
     */
    public Long getCreatedTime() {
        return createdTime;
    }

    /**
     * 注册时间
     * This method sets the value of the database column cys_user.created_time
     *
     * @param createdTime the value for cys_user.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Long createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cys_user
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getLoginName() == null ? other.getLoginName() == null : this.getLoginName().equals(other.getLoginName()))
            && (this.getPasswd() == null ? other.getPasswd() == null : this.getPasswd().equals(other.getPasswd()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getEmailStatus() == null ? other.getEmailStatus() == null : this.getEmailStatus().equals(other.getEmailStatus()))
            && (this.getMobileStatus() == null ? other.getMobileStatus() == null : this.getMobileStatus().equals(other.getMobileStatus()))
            && (this.getRegisterIp() == null ? other.getRegisterIp() == null : this.getRegisterIp().equals(other.getRegisterIp()))
            && (this.getUserStatus() == null ? other.getUserStatus() == null : this.getUserStatus().equals(other.getUserStatus()))
            && (this.getUpdatedTime() == null ? other.getUpdatedTime() == null : this.getUpdatedTime().equals(other.getUpdatedTime()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cys_user
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getLoginName() == null) ? 0 : getLoginName().hashCode());
        result = prime * result + ((getPasswd() == null) ? 0 : getPasswd().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getEmailStatus() == null) ? 0 : getEmailStatus().hashCode());
        result = prime * result + ((getMobileStatus() == null) ? 0 : getMobileStatus().hashCode());
        result = prime * result + ((getRegisterIp() == null) ? 0 : getRegisterIp().hashCode());
        result = prime * result + ((getUserStatus() == null) ? 0 : getUserStatus().hashCode());
        result = prime * result + ((getUpdatedTime() == null) ? 0 : getUpdatedTime().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cys_user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", loginName=").append(loginName);
        sb.append(", passwd=").append(passwd);
        sb.append(", email=").append(email);
        sb.append(", mobile=").append(mobile);
        sb.append(", emailStatus=").append(emailStatus);
        sb.append(", mobileStatus=").append(mobileStatus);
        sb.append(", registerIp=").append(registerIp);
        sb.append(", userStatus=").append(userStatus);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}